fun main(){
    println("Student Enrollment No.:")
    var num=readln().toInt()
    print("Student Name:")
    var name=readLine().toString()
    print("Student Age:")
    var age=readln().toInt()
    print("Student Branch:")
    var branch=readLine().toString()
    print("Student Class:")
    var cls=readLine().toString()
    print("Student Batch:")
    var batch=readLine().toString()
    print("Student College Name:")
    var clg_name=readLine().toString()
    print("Student University Name:")
    var uni_name=readLine().toString()
    println()
    println("**********************")
    println()
    println("Student's Data: ")
    println("Enrollment No.:$num")
    println("Name:$name")
    println("Age:$age")
    println("Branch:$branch")
    println("Class:$cls")
    println("Batch:$batch")
    println("College Name:$clg_name")
    println("University Name:$uni_name")
}